# Generated by Django 4.2.4 on 2023-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_candidat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre_id', models.BigIntegerField()),
                ('offre_soc', models.TextField()),
                ('offre_post', models.TextField()),
                ('offre_date', models.DateField()),
                ('offre_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidat',
            name='candidat_bacplus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='candidat_exper',
            field=models.IntegerField(),
        ),
    ]
