# Generated by Django 4.2.4 on 2023-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_candidatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrelogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entre_id', models.BigIntegerField()),
                ('entre_name', models.TextField()),
                ('entre_email', models.TextField()),
                ('entre_password', models.TextField()),
            ],
        ),
    ]
