# Generated by Django 4.2.4 on 2023-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0006_entrelogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_name', models.TextField()),
                ('message_email', models.TextField()),
                ('message_subject', models.TextField()),
                ('message_mess', models.TextField()),
            ],
        ),
    ]
