# Generated by Django 4.2.4 on 2023-08-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0008_remove_userlogin_id_alter_userlogin_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrelogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='entrelogin',
            name='entre_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
