# Generated by Django 4.2.4 on 2023-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0009_remove_entrelogin_id_alter_entrelogin_entre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='offre_adresse',
            field=models.TextField(default='maroc'),
        ),
    ]
