# Generated by Django 4.2.4 on 2023-09-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0010_offre_offre_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatures',
            name='candid_cv',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
