# Generated by Django 4.2.4 on 2023-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0011_candidatures_candid_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatures',
            name='candid_cv',
            field=models.FileField(upload_to=''),
        ),
    ]
