# Generated by Django 4.2.4 on 2023-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0012_alter_candidatures_candid_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlogin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_email', models.TextField()),
                ('admin_password', models.TextField()),
            ],
        ),
    ]
