# Generated by Django 4.2.4 on 2023-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0013_adminlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='admin_email',
            new_name='madmin_email',
        ),
        migrations.RenameField(
            model_name='adminlogin',
            old_name='admin_id',
            new_name='madmin_id',
        ),
        migrations.RenameField(
            model_name='adminlogin',
            old_name='admin_password',
            new_name='madmin_password',
        ),
    ]
