# Generated by Django 4.2.4 on 2023-09-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0014_rename_admin_email_adminlogin_madmin_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminlogin',
            new_name='Madminlogin',
        ),
    ]
