# Generated by Django 4.2.4 on 2023-09-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0015_rename_adminlogin_madminlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Madminlogin',
            new_name='Madlogin',
        ),
        migrations.RenameField(
            model_name='madlogin',
            old_name='madmin_email',
            new_name='mad_email',
        ),
        migrations.RenameField(
            model_name='madlogin',
            old_name='madmin_id',
            new_name='mad_id',
        ),
        migrations.RenameField(
            model_name='madlogin',
            old_name='madmin_password',
            new_name='mad_password',
        ),
    ]
