# Generated by Django 4.2.4 on 2023-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0017_delete_madlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hauptuser',
            fields=[
                ('huser_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('huser_email', models.TextField()),
                ('huser_password', models.TextField()),
            ],
        ),
    ]
