# Generated by Django 4.2.4 on 2023-09-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0022_alter_offre_offre_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='Offre_img',
            new_name='offre_img',
        ),
    ]
