# Generated by Django 4.2.4 on 2023-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0024_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('avis_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avis_name', models.TextField()),
                ('avis_post', models.TextField()),
                ('avis_eval', models.IntegerField()),
                ('avis_content', models.TextField()),
            ],
        ),
    ]
